export const portfolio = {
  name: "Achraf Ouakrim",
  role: "Graphic Designer & Vibecoder",
  location: "Tamesna, Morocco",
  email: "ouakrim.achraf@outlook.com",
  logo: "/assets/achraf-logo.svg",
  headline: "Achraf Ouakrim designs brands, packaging, visual campaigns, and digital experiences.",
  summary:
    "Graphic designer and vibecoder based in Tamesna, combining brand identity, packaging, print, and social visuals with thoughtful digital experiences.",
  availability: "Graphic designer at KARA Distribution since 2019",
  headshot: "/assets/optimized/achraf-portrait-vector.jpg",
  headshotAlt: "Portrait of Achraf Ouakrim",
  heroMetric: {
    value: "5+",
    label: "years shaping commercial design work",
  },
  resume: {
    label: "Download resume",
    href: "https://drive.google.com/file/d/100MhewVl13iIL_y0qF_k880nWJ7hlZiC/view?usp=sharing",
  },
  socials: [
    { label: "Instagram", href: "https://www.instagram.com/achrafouak.psd/" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/achraf-ouakrim-654778138/" },
    { label: "Behance", href: "https://www.behance.net/achraf_ouak" },
    { label: "Dribbble", href: "https://dribbble.com/Ash_Ouak" },
  ] as Array<{ label: string; href: string }>,
  services: [
    { title: "Brand identity", description: "Logos, identity systems, and visual direction with a clear point of view.", image: "/assets/optimized/phenix/logo.jpg", imageAlt: "Phenix Kitchen phoenix logo", href: "#identity" },
    { title: "Packaging", description: "B2B packaging systems designed from supplied identity to production-ready application.", image: "/assets/optimized/miam/paper-bag.jpg", imageAlt: "MIAM bakery paper bag packaging mockup", href: "#packaging" },
    { title: "Print design", description: "Menus, brochures, and printed formats designed for real-world reading and production.", image: "/assets/optimized/print-menus/gaston-gali-final-mockup.jpg", imageAlt: "Gaston Gali printed menu mockup", href: "#print" },
    { title: "Vehicle wrapping", description: "Large-format graphics that keep their impact in motion and at a distance.", image: "/assets/optimized/vehicle-wrapping/kara-renault-front.jpg", imageAlt: "KARA Distribution Renault vehicle wrap", href: "#vehicle-wrapping" },
    { title: "Animated posters", description: "Social media visuals and poster compositions built to catch attention quickly and consistently.", image: "/assets/optimized/posters/lost-vr.jpg", imageAlt: "Red and black editorial poster about virtual reality", href: "#poster-wall" },
  ],
  showcaseSections: [
    {
      id: "identity",
      label: "Brand identity",
      intro: "Identity systems that make a business recognizable.",
      description: "Logos, editorial assets, and practical applications built into a coherent brand presence.",
      projects: [
        {
          slug: "phenix-kitchen-identity",
          title: "Phenix Kitchen",
          meta: "Restaurant identity",
          scope: "Logo / brochure / letterhead / business card",
          href: "/work/phenix-kitchen-identity",
          images: [
            { src: "/assets/optimized/phenix/identity-mockup.jpg", alt: "Phenix Kitchen stationery and brochure mockup" },
            { src: "/assets/optimized/phenix/business-card-preview.jpg", alt: "Phenix Kitchen business card source artwork" },
            { src: "/assets/optimized/phenix/brochure-fr-preview.jpg", alt: "Phenix Kitchen French brochure source artwork" },
            { src: "/assets/optimized/phenix/brochure-ar-preview.jpg", alt: "Phenix Kitchen Arabic brochure source artwork" },
          ],
        },
      ],
    },
    {
      id: "packaging",
      label: "Packaging",
      intro: "Packaging systems built to move from supplied identity to production.",
      description: "B2B food-service and hospitality packaging across bags, cups, labels, boxes, and dielines.",
      projects: [
        { slug: "ikea-casablanca-packaging", title: "IKEA Morocco", meta: "Food-service packaging", scope: "Cups / bags / napkins / sandwich formats", href: "/work/ikea-casablanca-packaging", images: [{ src: "/assets/optimized/ikea/cups.jpg", alt: "IKEA Morocco paper cup packaging" }, { src: "/assets/optimized/ikea/sac-sand.jpg", alt: "IKEA Morocco sandwich bag packaging" }, { src: "/assets/optimized/ikea/serviette.jpg", alt: "IKEA Morocco napkin packaging" }, { src: "/assets/optimized/ikea/papier-tacos.jpg", alt: "IKEA Morocco taco paper packaging" }] },
        { slug: "miam-bakery-packaging", title: "MIAM bakery", meta: "Bakery packaging system", scope: "Labels / bags / cups / stickers", href: "/work/miam-bakery-packaging", images: [{ src: "/assets/optimized/miam/paper-bag.jpg", alt: "MIAM bakery paper bag packaging" }, { src: "/assets/optimized/miam/goblet-carton.jpg", alt: "MIAM bakery paper cup packaging" }, { src: "/assets/optimized/miam/round-label.jpg", alt: "MIAM bakery dessert label packaging" }, { src: "/assets/optimized/miam/stickers.jpg", alt: "MIAM bakery sticker packaging" }] },
        { slug: "cafe-bonjour-packaging", title: "Café Bonjour", meta: "Gas station food-service", scope: "Bags / cups / pastry box / fries pouch", href: "/work/cafe-bonjour-packaging", images: [{ src: "/assets/optimized/cafe-bonjour/goblet.jpg", alt: "Café Bonjour paper cup packaging" }, { src: "/assets/optimized/cafe-bonjour/tote-bag.jpg", alt: "Café Bonjour tote bag packaging" }, { src: "/assets/optimized/cafe-bonjour/pastry-box.jpg", alt: "Café Bonjour pastry box packaging" }, { src: "/assets/optimized/cafe-bonjour/fries-bag.jpg", alt: "Café Bonjour fries bag packaging" }] },
        { slug: "dar-dyafa-packaging", title: "Dar Dyafa", meta: "Restaurant packaging", scope: "Pizza boxes / bags / cups / fries pouch", href: "/work/dar-dyafa-packaging", images: [{ src: "/assets/optimized/dar-dyafa/pizza-box.jpg", alt: "Dar Dyafa pizza box packaging" }, { src: "/assets/optimized/dar-dyafa/tote-bag.jpg", alt: "Dar Dyafa tote bag packaging" }, { src: "/assets/optimized/dar-dyafa/goblet.jpg", alt: "Dar Dyafa paper cup packaging" }, { src: "/assets/optimized/dar-dyafa/fries-bag.jpg", alt: "Dar Dyafa fries bag packaging" }] },
        { slug: "ram-airline-packaging", title: "Royal Air Maroc", meta: "Airline hospitality", scope: "Cups / napkins / onboard service details", href: "/work/ram-airline-packaging", images: [{ src: "/assets/optimized/ram/cup-beige.jpg", alt: "Royal Air Maroc beige paper cup" }, { src: "/assets/optimized/ram/napkin-beige.jpg", alt: "Royal Air Maroc beige napkin" }, { src: "/assets/optimized/ram/napkin-red.jpg", alt: "Royal Air Maroc red napkin" }, { src: "/assets/optimized/ram/napkin-white.jpg", alt: "Royal Air Maroc white napkin" }] },
        { slug: "royale-mansour-packaging", title: "Royale Mansour", meta: "Luxury hotel packaging", scope: "Food-service packaging / premium applications", href: "/work/royale-mansour-packaging", images: [{ src: "/assets/optimized/royale-mansour/sandwich-paper.jpg", alt: "Royale Mansour sandwich paper packaging" }, { src: "/assets/optimized/royale-mansour/fries-bag.jpg", alt: "Royale Mansour fries bag packaging" }, { src: "/assets/optimized/royale-mansour/paper-bowl.jpg", alt: "Royale Mansour paper bowl packaging" }, { src: "/assets/optimized/royale-mansour/burger-box.jpg", alt: "Royale Mansour burger box packaging" }] },
        { slug: "chilis-packaging", title: "Chili's", meta: "Restaurant packaging", scope: "Sandwich paper / napkins / stickers / bags", href: "/work/chilis-packaging", images: [{ src: "/assets/optimized/chilis/sandwich-paper.jpg", alt: "Chili's sandwich paper packaging" }, { src: "/assets/optimized/chilis/napkin.jpg", alt: "Chili's napkin packaging" }, { src: "/assets/optimized/chilis/stickers.jpg", alt: "Chili's sticker roll packaging" }, { src: "/assets/optimized/chilis/tote-bag.jpg", alt: "Chili's kraft bag packaging" }] },
        { slug: "huawei-packaging", title: "Huawei Northern Africa", meta: "Corporate hospitality", scope: "Coffee cups / reusable bags / event applications", href: "/work/huawei-packaging", images: [{ src: "/assets/optimized/huawei/bag.jpg", alt: "Huawei Northern Africa reusable bag" }, { src: "/assets/optimized/huawei/cup.jpg", alt: "Huawei Northern Africa paper coffee cup" }] },
        { slug: "dune-creme-packaging", title: "Dune Crème", meta: "Bakery packaging", scope: "Labels / kraft bags / napkins / sugar sachets", href: "/work/dune-creme-packaging", images: [{ src: "/assets/optimized/dune-creme/labels.jpg", alt: "Dune Crème label roll" }, { src: "/assets/optimized/dune-creme/tote-bag.jpg", alt: "Dune Crème kraft tote bag" }, { src: "/assets/optimized/dune-creme/napkin.jpg", alt: "Dune Crème napkin packaging" }] },
        { slug: "quince-packaging", title: "QUINCE", meta: "Coffee and chocolat", scope: "4 oz / 8 oz / 12 oz cup system", href: "/work/quince-packaging", images: [{ src: "/assets/optimized/quince/cups.jpg", alt: "QUINCE coffee cup system" }] },
        { slug: "keat-packaging", title: "Keat", meta: "Food box packaging", scope: "White and kraft box directions", href: "/work/keat-packaging", images: [{ src: "/assets/optimized/keat/boxes.jpg", alt: "Keat food box packaging" }] },
      ],
    },
    {
      id: "print",
      label: "Print design",
      intro: "Print pieces designed to be held, read, and remembered.",
      description: "Menus, product packaging, and printed systems with clear hierarchy and production-ready files.",
      projects: [
        {
          slug: "gaston-gali-menu-print",
          title: "Gaston Gali menus",
          meta: "Restaurant menu design",
          scope: "Menu cover / interior menu system",
          href: "/work/gaston-gali-menu-print",
          images: [
            { src: "/assets/optimized/print-menus/gaston-gali-final-mockup.jpg", alt: "Gaston Gali open menu mockup" },
            { src: "/assets/optimized/print-menus/gaston-gali-menu-mockup.jpg", alt: "Gaston Gali printed menu mockup" },
          ],
        },
        {
          slug: "karty-freezing-bag-print",
          title: "Karty freezing bag",
          meta: "Product packaging print",
          scope: "Frozen-food bag artwork / production layout",
          href: "/work/karty-freezing-bag-print",
          images: [
            { src: "/assets/optimized/print-menus/karty-freezing-bag.jpg", alt: "Karty freezing bag printed packaging" },
          ],
        },
        {
          slug: "sopalin-print-range",
          title: "Sopalin paper range",
          meta: "Consumer packaging print",
          scope: "Eco / Jumbo / Maxi printed roll systems",
          href: "/work/sopalin-print-range",
          images: [
            { src: "/assets/optimized/print-menus/sopalin/sopalin-eco.jpg", alt: "Sopalin Eco printed roll packaging" },
            { src: "/assets/optimized/print-menus/sopalin/sopalin-jumbo.jpg", alt: "Sopalin Jumbo printed roll packaging" },
            { src: "/assets/optimized/print-menus/sopalin/sopalin-maxi.jpg", alt: "Sopalin Maxi printed roll packaging" },
          ],
        },
      ],
    },
    {
      id: "vehicle-wrapping",
      label: "Vehicle wrapping",
      intro: "Brand systems that move through the city.",
      description: "Large-format applications designed to remain legible, recognizable, and useful from every angle.",
      projects: [
        {
          slug: "kara-renault-vehicle-wrap",
          title: "KARA Distribution",
          meta: "Renault vehicle wrap",
          scope: "Fleet graphics / contact information / front and rear views",
          href: "/work/kara-renault-vehicle-wrap",
          images: [
            { src: "/assets/optimized/vehicle-wrapping/kara-renault-front.jpg", alt: "KARA Distribution Renault vehicle wrap front view" },
            { src: "/assets/optimized/vehicle-wrapping/kara-renault-rear.jpg", alt: "KARA Distribution Renault vehicle wrap rear view" },
          ],
        },
      ],
    },
    {
      id: "posters",
      label: "Animated posters",
      intro: "Poster systems built to stop the scroll.",
      description: "Social media visuals, sports posters, and editorial compositions with a strong visual point of view.",
      projects: [
        {
          slug: "football-poster-series",
          title: "Morocco football series",
          meta: "Sports campaign visuals",
          scope: "Africa Cup / World Cup / match-day compositions",
          href: "https://www.behance.net/achraf_ouak",
          external: true,
          images: [
            { src: "/assets/optimized/football-filers.jpg", alt: "Morocco football road to the final poster" },
            { src: "/assets/optimized/football-la-casa.jpg", alt: "Morocco versus Zambia football poster" },
            { src: "/assets/optimized/football-match-day.jpg", alt: "Morocco team celebration poster" },
            { src: "/assets/optimized/football-world-cup.jpg", alt: "Morocco World Cup poster" },
          ],
        },
        {
          slug: "editorial-poster-archive",
          title: "Editorial poster archive",
          meta: "Social media visuals",
          scope: "Kufi typography / Green March / VR editorial / campaign posters",
          href: "https://www.behance.net/achraf_ouak",
          external: true,
          images: [
            { src: "/assets/optimized/posters/lost-vr.jpg", alt: "The Illusion of Connection VR editorial poster" },
            { src: "/assets/optimized/poster-kuffi-typography.jpg", alt: "Kufi typography poster" },
            { src: "/assets/optimized/poster-green-march-47.jpg", alt: "47th Green March anniversary poster" },
            { src: "/assets/optimized/poster-kara-new-year.jpg", alt: "KARA Distribution New Year poster" },
          ],
        },
      ],
    },
  ],
  packagingProjects: [
    { slug: "ikea-casablanca-packaging", title: "IKEA Morocco / Casablanca food packaging", meta: "B2B packaging / Dielines and applications" },
    { slug: "miam-bakery-packaging", title: "MIAM bakery packaging system", meta: "Bakery identity / Labels, bags and food packaging" },
    { slug: "cafe-bonjour-packaging", title: "Café Bonjour food-service packaging", meta: "Gas station / Takeaway packaging system" },
    { slug: "dar-dyafa-packaging", title: "Dar Dyafa restaurant packaging", meta: "Restaurant identity / Boxes, bags and cups" },
    { slug: "ram-airline-packaging", title: "Royal Air Maroc onboard packaging", meta: "Airline hospitality / Cups and napkins" },
    { slug: "royale-mansour-packaging", title: "Royale Mansour luxury hotel packaging", meta: "Luxury hospitality / Food-service packaging" },
    { slug: "chilis-packaging", title: "Chili's restaurant packaging", meta: "Restaurant identity / Paper, bags and labels" },
    { slug: "huawei-packaging", title: "Huawei Northern Africa packaging", meta: "Corporate hospitality / Bags and coffee cups" },
    { slug: "dune-creme-packaging", title: "Dune Crème bakery packaging", meta: "Bakery identity / Labels, bags and table service" },
    { slug: "quince-packaging", title: "QUINCE coffee cup system", meta: "Coffee and chocolat / 4 oz, 8 oz and 12 oz cups" },
    { slug: "keat-packaging", title: "Keat food box packaging", meta: "Food packaging / White and kraft box directions" },
  ],
  identityProjects: [
    { slug: "phenix-kitchen-identity", title: "Phenix Kitchen restaurant identity", meta: "Logo / Brochure / Letterhead / Business card" },
  ],
  printProjects: [
    { slug: "gaston-gali-menu-print", title: "Restaurant and commercial print collection", meta: "Print design / Menus and frozen-food packaging" },
  ],
  vehicleWrappingProjects: [
    { slug: "kara-renault-vehicle-wrap", title: "KARA Distribution / Renault vehicle wrap", meta: "Vehicle wrapping / Fleet graphics and contact information" },
  ],
  projects: [
    {
      title: "Road to the Final",
      role: "Personal football poster series",
      problem: "Built a cinematic match-day poster around Morocco's journey through the Africa Cup of Nations.",
      outcome: "Combined player portraits, filmstrip framing, match information, and editorial typography into one campaign visual.",
      stack: ["Photoshop", "Photo compositing", "Sports campaign"],
      image: "/assets/optimized/football-filers.jpg",
      imageAlt: "Football poster showing Morocco players on a road to the final",
      links: [{ label: "More on Behance", href: "https://www.behance.net/achraf_ouak" }],
    },
    {
      title: "Morocco vs Zambia",
      role: "Match-day visual concept",
      problem: "Created a dramatic visual identity for a Morocco match using a cinematic, character-led composition.",
      outcome: "Used layered characters, controlled lighting, and bold red typography to create a high-energy poster.",
      stack: ["Photoshop", "Compositing", "Typography"],
      image: "/assets/optimized/football-la-casa.jpg",
      imageAlt: "Cinematic Morocco versus Zambia football poster",
      links: [{ label: "More on Behance", href: "https://www.behance.net/achraf_ouak" }],
    },
    {
      title: "Africa Match Day",
      role: "Sports campaign visual",
      problem: "Turned a team celebration into a bold, shareable visual for a football audience.",
      outcome: "Created a layered celebration scene with a bright pink-red treatment, action framing, and tournament branding.",
      stack: ["Photoshop", "Image treatment", "Campaign design"],
      image: "/assets/optimized/football-match-day.jpg",
      imageAlt: "Morocco team celebration football poster",
      links: [{ label: "More on Behance", href: "https://www.behance.net/achraf_ouak" }],
    },
    {
      title: "African Cup",
      role: "Poster design",
      problem: "Explored how a trophy, players, and a national team story could share one editorial composition.",
      outcome: "Balanced oversized display type, layered football imagery, and tournament marks in a warm, celebratory poster.",
      stack: ["Photoshop", "Editorial layout", "Art direction"],
      image: "/assets/optimized/football-african-cup.jpg",
      imageAlt: "African Cup football poster with Morocco players and trophy",
      links: [{ label: "More on Behance", href: "https://www.behance.net/achraf_ouak" }],
    },
    {
      title: "Make Us Dream",
      role: "World Cup poster concept",
      problem: "Captured the emotion and collective energy around Morocco's 2022 World Cup run.",
      outcome: "Built a layered team portrait with a strong magenta field, tournament references, and a repeated message system.",
      stack: ["Photoshop", "Photo montage", "Sports graphics"],
      image: "/assets/optimized/football-world-cup.jpg",
      imageAlt: "Morocco World Cup poster with players and magenta background",
      links: [{ label: "More on Behance", href: "https://www.behance.net/achraf_ouak" }],
    },
  ],
  posters: [
    { title: "Road to the Final", image: "/assets/optimized/football-filers.jpg", alt: "Football poster showing Morocco players on a road to the final" },
    { title: "Morocco vs Zambia", image: "/assets/optimized/football-la-casa.jpg", alt: "Cinematic Morocco versus Zambia football poster" },
    { title: "Africa Match Day", image: "/assets/optimized/football-match-day.jpg", alt: "Morocco team celebration football poster" },
    { title: "African Cup", image: "/assets/optimized/football-african-cup.jpg", alt: "African Cup football poster with Morocco players and trophy" },
    { title: "Make Us Dream", image: "/assets/optimized/football-world-cup.jpg", alt: "Morocco World Cup poster with players and magenta background" },
    { title: "KARA Distribution New Year", image: "/assets/optimized/poster-kara-new-year.jpg", alt: "KARA Distribution New Year poster in a warehouse" },
    { title: "Kufi Typography", image: "/assets/optimized/poster-kuffi-typography.jpg", alt: "Kufi Arabic typography poster in cream and dark green" },
    { title: "Next Match", image: "/assets/optimized/poster-next-match-clean.jpg", alt: "Cleaned Morocco versus Tanzania next match poster" },
    { title: "47th Green March Anniversary", image: "/assets/optimized/poster-green-march-47.jpg", alt: "Bilingual Moroccan poster commemorating the 47th Green March Anniversary" },
    { title: "The Illusion of Connection", image: "/assets/optimized/posters/lost-vr.jpg", alt: "Red and black editorial poster about the dystopian implications of VR headsets" },
  ],
  capabilities: [
    {
      title: "Brand and identity",
      description: "Logo design, brand identity systems, and consistent visual direction for commercial communication.",
    },
    {
      title: "Print and packaging",
      description: "Catalogues, flyers, brochures, packaging, and production-aware layouts for physical formats.",
    },
    {
      title: "Digital campaigns",
      description: "Social media posters, banners, and adaptable visuals for recurring campaign needs.",
    },
  ],
  skills: [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Figma",
    "Blender",
    "Logo design",
    "Brand identity",
    "Packaging design",
    "Catalogues",
    "Flyers",
    "Vehicle wrapping",
    "Social media posters",
    "Social media banners",
  ],
  languages: ["Arabic", "English", "French"],
  qualities: ["Team spirit", "Creativity", "Dynamism", "Adaptability"],
  experience: [
    {
      title: "Graphic Designer",
      company: "KARA Distribution",
      location: "Tamesna",
      period: "Nov. 2019 - Present",
      details: [
        "Catalogues and flyers",
        "Vehicle wrapping",
        "Packaging design",
        "Social media posters and banners",
        "Logo and brand identity",
      ],
    },
    {
      title: "Graphic Design Intern",
      company: "PANO SIGN SERVICE",
      location: "Temara",
      period: "May 2018 - Jul. 2018",
      details: ["Brochures", "Flyers", "Vehicle wrapping", "T-shirt design concepts"],
    },
    {
      title: "Graphic Design Intern",
      company: "2BROTHERS",
      location: "Casablanca",
      period: "Jan. 2017 - Mar. 2017",
      details: ["Early professional graphic design experience"],
    },
  ],
  education: [
    "Specialized Technician in Infographics, OFPPT Rabat, 2016-2018",
    "English Studies, Faculty of Letters and Human Sciences Rabat, 2014-2016",
    "Baccalaureate, Lycee Moulay Abdellah Rabat, 2014",
  ],
  about: {
    title: "A designer focused on clear commercial visuals.",
    paragraphs: [
      "My work sits across brand identity, print design, packaging, and campaign visuals. I like designs that are easy to understand, useful for the business, and strong enough to hold attention.",
      "I bring creativity, adaptability, team spirit, and steady execution to visual projects that need to move from idea to finished asset.",
    ],
  },
  contact: {
    title: "Let’s create the next visual identity, campaign, or print piece.",
    description:
      "Reach out for graphic design roles, brand work, packaging, print materials, or social media visuals.",
  },
};
